/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.intesoft.puntoventa.formularios;

import com.intesoft.puntoventa.controller.OperacionController;
import com.intesoft.puntoventa.entity.Operacion;
import com.intesoft.puntoventa.entity.Usuarios;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Usuario
 */
public class Egresos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Egresos
     */
    TableRowSorter<DefaultTableModel> sorter;
    DefaultTableModel model;
    private List<Operacion> listOperacion;
    private Usuarios usuarios;
    private OperacionController operacionController;

    public Egresos() {
        initComponents();

    }

    public Egresos(Usuarios usuarios) {
        initComponents();
        this.usuarios = usuarios;
        this.listOperacion = new ArrayList<>();

        this.model = (DefaultTableModel) jTable1.getModel();
        this.jTable1.setModel(model);
        this.jTable1.setAutoCreateRowSorter(true);
        sorter = new TableRowSorter<>(model);
        this.jTable1.setRowSorter(sorter);
        operacionController = new OperacionController();

        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Jt_Gastos = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Jf_TotalGastod = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setTitle("Egresos");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gastos.png"))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Descripcion", "Fecha", "Reporta", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Costos:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/contabilidad.png"))); // NOI18N
        jButton1.setText("Ingresar Gastos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo Gasto:");

        jLabel3.setText("Total Gastos:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "SERVICIOS", "ALIMENTACION", "NOMINA", "MANTENIMIENTO" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(Jt_Gastos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(0, 360, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Jf_TotalGastod, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Jt_Gastos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jf_TotalGastod, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String gasto = Jt_Gastos.getText();
        int tipoGasto = jComboBox1.getSelectedIndex();
        if (!gasto.isEmpty() && tipoGasto != 0) {
            int respuesta = JOptionPane.showConfirmDialog(null, "¿Quieres guardar este gasto? \n"
                    + jComboBox1.getSelectedItem().toString() + " por valor de " + gasto, "Confirmación", JOptionPane.YES_NO_OPTION);
            if (respuesta == JOptionPane.YES_OPTION) {
                double gastoNum = Double.parseDouble(gasto);
            gastoNum = gastoNum * -1;
            Operacion operacion = new Operacion();
            operacion.setFecha(new Date());
            operacion.setOperacion(jComboBox1.getSelectedItem().toString());
            operacion.setUsuario(this.usuarios.getNombres() + " " + this.usuarios.getApellidos());
            operacion.setValor(gastoNum);
            int id = operacionController.saveOperacion(operacion);
            updateTable();
            JOptionPane.showMessageDialog(null, "El egreso " + id + " ha sido registrado con exito", "Advertencia", JOptionPane.WARNING_MESSAGE);
            } else {
                // El usuario seleccionó "No" o cerró el cuadro de diálogo, puedes manejarlo aquí si es necesario
                System.out.println("No se realizó la acción.");
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Debe ingresar el tipo de gasto y el valor del mismo", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void updateTable() {
        OperacionController operacionController = new OperacionController();
        listOperacion = operacionController.getAllEgresos();
        this.model.setNumRows(0);
        for (Operacion operacion : listOperacion) {
            Object[] rowData = {
                operacion.getIdOperacion(),
                operacion.getOperacion(),
                operacion.getFecha(),
                operacion.getUsuario(),
                operacion.getValor()
            };
            this.model.addRow(rowData);

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField Jf_TotalGastod;
    private javax.swing.JTextField Jt_Gastos;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
