/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.intesoft.puntoventa.formularios;

import com.intesoft.puntoventa.controller.CreditoController;
import com.intesoft.puntoventa.controller.OperacionController;
import com.intesoft.puntoventa.controller.RegistroVendidoController;
import com.intesoft.puntoventa.controller.ResumenFinancieroController;
import com.intesoft.puntoventa.dto.IngresosDto;
import com.intesoft.puntoventa.entity.ResumenFinanciero;
import com.intesoft.puntoventa.util.MonedaTransform;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class Ingresos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Ingresos
     */
    private List<IngresosDto> listIngresosDto;
    private RegistroVendidoController registroVendidoController;
    private MonedaTransform monedaTransform;
    private ResumenFinancieroController resumenFinancieroController;
    private ResumenFinanciero resumenFinanciero;
    public Ingresos() {
        initComponents();
        monedaTransform = new MonedaTransform();
        // Obtén la fecha actual
        Calendar calendar = Calendar.getInstance();
        
        // Resta 7 días a la fecha actual
        calendar.add(Calendar.DAY_OF_YEAR, -7);
        
        // Convierte el resultado de nuevo a un objeto Date
        Date nuevaFecha = calendar.getTime();
        
        startJDateChooser.setDate(nuevaFecha);
        endJDateChooser.setDate(new Date());
        updateTable();
        valorCajaTextField.setEditable(false);
        Jf_totalGanancias.setEditable(false);
        Jf_totalVentas.setEditable(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Jf_totalVentas = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        Jf_totalGanancias = new javax.swing.JFormattedTextField();
        startJDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        endJDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        valorCajaTextField = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Ingresos");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/crecimiento-del-dinero.png"))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Id Operacion", "Codigo", "Descripcion", "Talla", "Color", "Tipo Operacion", "Fecha", "Usuario", "Cantidad", "Valor Compra", "Valor Venta", "Ganancia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Total Ventas:");

        jLabel2.setText("Total Ganancias");

        startJDateChooser.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                startJDateChooserPropertyChange(evt);
            }
        });

        jLabel4.setText("Fecha Inicial");

        jLabel5.setText("Fecha Final");

        endJDateChooser.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                endJDateChooserPropertyChange(evt);
            }
        });

        jLabel3.setText("Valor en Caja:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(valorCajaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Jf_totalGanancias, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Jf_totalVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(startJDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(endJDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(startJDateChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endJDateChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Jf_totalVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jf_totalGanancias, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(valorCajaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startJDateChooserPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_startJDateChooserPropertyChange
        updateTable();
    }//GEN-LAST:event_startJDateChooserPropertyChange

    private void endJDateChooserPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_endJDateChooserPropertyChange
        updateTable();
    }//GEN-LAST:event_endJDateChooserPropertyChange
    private void totalizarCaja(){
        resumenFinancieroController  = new ResumenFinancieroController();
        resumenFinanciero = resumenFinancieroController.getTotalCaja();
        valorCajaTextField.setText(monedaTransform.formatMoneda(resumenFinanciero.getTotalAbonosNoPagado() 
                + resumenFinanciero.getTotalCajaVenta()+ resumenFinanciero.getTotalAbonosNoPagado()));
        
    }
    private void updateTable(){
        registroVendidoController = new RegistroVendidoController();
        Date startDate = startJDateChooser.getDate();
        Date endDate = endJDateChooser.getDate();
        listIngresosDto = registroVendidoController.getIngresosByDateRange(startDate, endDate );
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setNumRows(0);
        double ganacia = 0;
        double totalGanacia = 0;
        double totalVenta = 0;
        for (IngresosDto ingresosDto : listIngresosDto) {
            ganacia = (ingresosDto.getValorVenta()- ingresosDto.getValorCompra());
            totalVenta += ingresosDto.getValorVenta();
            totalGanacia += ganacia;
            Object[] rowData = {
                ingresosDto.getId(),
                ingresosDto.getIdOperacion(),
                ingresosDto.getCodigo(),
                ingresosDto.getDescripcion(),
                ingresosDto.getTalla(),
                ingresosDto.getColor(),
                ingresosDto.getTipoOperacion(),
                ingresosDto.getFecha(),
                ingresosDto.getUsuario(),
                ingresosDto.getCantidad(),
                monedaTransform.formatMoneda(ingresosDto.getValorCompra()),
                monedaTransform.formatMoneda(ingresosDto.getValorVenta()),
                monedaTransform.formatMoneda(ganacia)
            };
            model.addRow(rowData);
            
        }
        Jf_totalVentas.setText(monedaTransform.formatMoneda(totalVenta));
        Jf_totalGanancias.setText(monedaTransform.formatMoneda(totalGanacia));
        totalizarCaja();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField Jf_totalGanancias;
    private javax.swing.JFormattedTextField Jf_totalVentas;
    private com.toedter.calendar.JDateChooser endJDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private com.toedter.calendar.JDateChooser startJDateChooser;
    private javax.swing.JTextField valorCajaTextField;
    // End of variables declaration//GEN-END:variables
}
