/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.intesoft.puntoventa.formularios;

import com.intesoft.puntoventa.controller.InventarioController;
import com.intesoft.puntoventa.controller.RegistroVendidoController;
import com.intesoft.puntoventa.controller.VentasController;
import com.intesoft.puntoventa.dto.InventarioDto;
import com.intesoft.puntoventa.entity.Inventario;
import com.intesoft.puntoventa.entity.RegistroVendido;
import com.intesoft.puntoventa.entity.Usuarios;
import com.intesoft.puntoventa.entity.Operacion;
import com.intesoft.puntoventa.util.MonedaTransform;
import com.intesoft.puntoventa.util.Operaciones;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class Ventas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Ventas
     */
    Usuarios usuarios;
    InventarioController inventarioController;
    Inventario inventario;
    List<RegistroVendido> listRegistroVendidos;
    double totalVenta;
    int item = 0;
    MonedaTransform monedaTransform;
    public Ventas() {
        initComponents();
    }
    public Ventas(Usuarios usuarios) {
        this.usuarios = usuarios;
        initComponents();
        this.jLNombre.setText(this.usuarios.getNombres());
        this.jLRol.setText(this.usuarios.getRol());
        listRegistroVendidos = new ArrayList<>();
        monedaTransform = new MonedaTransform();
        this.buttonGroup1.add(jRadioVenta);
        this.buttonGroup1.add(jRadioSeparar);
        this.buttonGroup1.add(jRadioCredito);
        this.jRadioVenta.setSelected(true);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLRol = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextFCodigo = new javax.swing.JTextField();
        jTextFDescripcion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFCantidad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFValor = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFDescuento = new javax.swing.JTextField();
        jRadioVenta = new javax.swing.JRadioButton();
        jRadioSeparar = new javax.swing.JRadioButton();
        jRadioCredito = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLTotal = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFPago = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Ventas");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/compras.png"))); // NOI18N

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Item", "Codigo", "Descripcion", "Talla", "Color", "Cantidad", "Descuento", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(0);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(2).setMinWidth(5);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(350);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(5).setMaxWidth(150);
            jTable1.getColumnModel().getColumn(6).setMinWidth(10);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(1);
            jTable1.getColumnModel().getColumn(8).setPreferredWidth(3);
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Usuario:");

        jLNombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLNombre.setText("asierra");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Rol:");

        jLRol.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLRol.setText("Vendedor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLRol, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLRol, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setText("Codigo:");

        jTextFDescripcion.setEditable(false);
        jTextFDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFDescripcionActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel7.setText("Descripcion:");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel8.setText("Cantidad:");

        jTextFCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFCantidadKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel9.setText("Precio:");

        jTextFValor.setEditable(false);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar mediano.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setText("Ingrese los productos de la venta");

        jLabel2.setText("Descuento:");

        jTextFDescuento.setToolTipText("");
        jTextFDescuento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFDescuentoKeyTyped(evt);
            }
        });

        jRadioVenta.setText("Venta");

        jRadioSeparar.setText("Separar");

        jRadioCredito.setText("Credito");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFDescripcion)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioVenta)
                                    .addComponent(jRadioSeparar)
                                    .addComponent(jRadioCredito))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFValor))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel11)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioVenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioSeparar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioCredito)
                        .addContainerGap())))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("Total a pagar");

        jLTotal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLTotal.setText("$. ");

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setText("Cambio");

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setText("$. ");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setText("Paga");

        jTextFPago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFPagoKeyTyped(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pagar.png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar mediano.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel21.setText("Ingrese los datos del pago");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFPago, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(14, 14, 14)
                        .addComponent(jLTotal))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 956, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(48, 48, 48)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFDescripcionActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        String code = this.jTextFCodigo.getText();
        if( code.isBlank()){
            JOptionPane.showMessageDialog(null, "Debe ingresar el codigo o parte del mismo para buscar", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        inventarioController = new InventarioController();
        int codigo = Integer.parseInt(this.jTextFCodigo.getText());
        List<InventarioDto> listaInventario = inventarioController.searchProducto(codigo);
        SeleccionProducto seleccionProducto = new SeleccionProducto(listaInventario, this);
        seleccionProducto.setModal(true);
        seleccionProducto.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        String cantidad = this.jTextFCantidad.getText() ;
        String code = this.jTextFCodigo.getText();
        String descuento =this.jTextFDescuento.getText();
        RegistroVendido registroVendido = new RegistroVendido();
        if(code.isBlank() || this.inventario == null ){
            JOptionPane.showMessageDialog(null, "Debe ingresar un producto valido", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!cantidad.isBlank() && Integer.parseInt(cantidad ) > 0) {
        
            registroVendido.setId(this.inventario.getId());
            registroVendido.setCodigo(this.inventario.getCodigo().getCodigo());
            registroVendido.setDescripcion(this.inventario.getCodigo().getDescripcion());
            registroVendido.setTalla(this.inventario.getCodigo().getTalla());
            registroVendido.setColor(this.inventario.getCodigo().getColor());
            registroVendido.setCantidad(Integer.parseInt(this.jTextFCantidad.getText()));
            registroVendido.setValorCompra(this.inventario.getValorCompra() * Integer.parseInt(this.jTextFCantidad.getText()));
            registroVendido.setIva(this.inventario.getIva());
            registroVendido.setTotalCompra(this.inventario.getTotalCompra() * Integer.parseInt(this.jTextFCantidad.getText()));
            registroVendido.setPorcentajeGananciaE(this.inventario.getPorcentajeGanancia());
            registroVendido.setPorcentajeGananciaR((float)((monedaTransform.transfrormMoneda(this.jTextFValor.getText())/this.inventario.getTotalCompra())-1));
            if (descuento.isBlank()) {
                registroVendido.setDescuento(0);
            }else{
            registroVendido.setDescuento(monedaTransform.transfrormMoneda(descuento));
            }
            registroVendido.setValorVenta( monedaTransform.transfrormMoneda(this.jTextFValor.getText()));
            totalVenta += (monedaTransform.transfrormMoneda(this.jTextFValor.getText()));
            this.jLTotal.setText(monedaTransform.formatMoneda(totalVenta));
            listRegistroVendidos.add(registroVendido);
            this.jTextFCodigo.setText("");
            this.jTextFCantidad.setText("");
            this.jTextFDescuento.setText("");
            this.jTextFDescripcion.setText("");
            this.jTextFValor.setText("");
            updateTable();
        }else{
            JOptionPane.showMessageDialog(null, "Lacantida debe ser diferente de cero", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        
        
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        VentasController ventasController = new VentasController();
        int numeroVenta = ventasController.saveVentas(monedaTransform.transfrormMoneda(this.jLTotal.getText()),jLNombre.getText(),Operaciones.VENTA.toString());
        Operacion venta = new Operacion();
        venta = ventasController.getVentaById(numeroVenta);
        for(RegistroVendido registroVendido : this.listRegistroVendidos){
            InventarioController inventarioController = new InventarioController();
            inventarioController.updateInventario(registroVendido.getId(), registroVendido.getCantidad());
            registroVendido.setId(0);
            registroVendido.setVenta(venta);
            
        }
        RegistroVendidoController registroVendidoController = new RegistroVendidoController();
        registroVendidoController.saveProductosVenta(this.listRegistroVendidos);
        DefaultTableModel model = (DefaultTableModel) this.jTable1.getModel();
        model.setNumRows(0);
        this.jTextFCodigo.setText("");
        this.jTextFCantidad.setText("");
        this.jTextFDescuento.setText("");
        this.jTextFDescripcion.setText("");
        this.jTextFValor.setText("");
        this.jLTotal.setText("$");
        this.jLabel16.setText("$");
        this.jTextFPago.setText("");
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jTextFCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFCantidadKeyTyped
        String descuento = this.jTextFDescuento.getText();
        if (descuento.isBlank()) {
            descuento = "0";
        }
        char []p={'1','2','3','4','5','6','7','8','9','0','\b','\0'};
        int b=0;
        for(int i=0; i<p.length ;i++){
            if(evt.getKeyChar() == '\b' || evt.getKeyChar() == '\0'){
                return;
            }else if (p[i] == evt.getKeyChar() && Integer.parseInt(this.jTextFCantidad.getText()+String.valueOf(evt.getKeyChar())) <= this.inventario.getCantidad()){
                b=1;
            }
            
        }
        if(b==0){
            evt.consume();
            JOptionPane.showMessageDialog(null, "La cantidad supera el stock o \n no es un caracter valido", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        double valor = this.inventario.getValorVenta()* (Double.parseDouble(this.jTextFCantidad.getText()+ String.valueOf(evt.getKeyChar())));
        this.jTextFValor.setText(monedaTransform.formatMoneda(valor - Double.parseDouble(descuento)));
    }//GEN-LAST:event_jTextFCantidadKeyTyped

    private void jTextFDescuentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFDescuentoKeyTyped
        String cantidad = jTextFCantidad.getText();
        String descuento = this.jTextFDescuento.getText();
        boolean flag = false;
        if (descuento.isBlank()) {
            descuento = "0";
            flag = true;
        }
        if (cantidad.isBlank()) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Debe ingresar una cantidad valida", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        char []p={'1','2','3','4','5','6','7','8','9','0','\b','\0'};
        int b=0;
        for(int i=0; i<p.length ;i++){
            if (p[i] == evt.getKeyChar()){
                String letra = String.valueOf(evt.getKeyChar());
                String actual = this.jTextFDescuento.getText();
                evt.consume();
                if (flag) {
                    this.jTextFDescuento.setText(monedaTransform.formatMoneda(Double.parseDouble(letra)));
                }else{
                    String monedalimpia = String.valueOf(monedaTransform.transfrormMoneda(actual));
                    monedalimpia= monedalimpia.substring(0,monedalimpia.length()-2);
                    this.jTextFDescuento.setText(monedaTransform.formatMoneda(Double.parseDouble(monedalimpia+letra)));
                }
                double valor = this.inventario.getValorVenta()* Double.parseDouble(jTextFCantidad.getText());
                this.jTextFValor.setText(monedaTransform.formatMoneda(valor - monedaTransform.transfrormMoneda(this.jTextFDescuento.getText())));
                return;
            }

        }
       
            evt.consume();
            JOptionPane.showMessageDialog(null, "No es un caracter valido", "Advertencia", JOptionPane.WARNING_MESSAGE);
          
        
    }//GEN-LAST:event_jTextFDescuentoKeyTyped

    private void jTextFPagoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFPagoKeyTyped
        String total = String.valueOf(monedaTransform.transfrormMoneda(jLTotal.getText()));
        String pago = jTextFPago.getText();
        boolean flag = false;
        if (pago.isBlank()) {
            pago = "0";
            flag = true;
        }
        if (total.isBlank()) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Debe tener productos sepsrado para vender", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        char []p={'1','2','3','4','5','6','7','8','9','0','\b','\0'};
        int b=0;
        for(int i=0; i<p.length ;i++){
            if (p[i] == evt.getKeyChar()){
                String letra = String.valueOf(evt.getKeyChar());
                String actual = this.jTextFPago.getText();
                evt.consume();
                if (flag) {
                    this.jTextFPago.setText(monedaTransform.formatMoneda(Double.parseDouble(letra)));
                }else{
                    String monedalimpia = String.valueOf(monedaTransform.transfrormMoneda(actual));
                    monedalimpia= monedalimpia.substring(0,monedalimpia.length()-2);
                    this.jTextFPago.setText(monedaTransform.formatMoneda(Double.parseDouble(monedalimpia+letra)));
                    this.jLabel16.setText(monedaTransform.formatMoneda(
                            monedaTransform.transfrormMoneda(jTextFPago.getText())-monedaTransform.transfrormMoneda(jLTotal.getText())));
                }
                return;
            }

        }
        
        evt.consume();
        JOptionPane.showMessageDialog(null, "No es un caracter valido", "Advertencia", JOptionPane.WARNING_MESSAGE);
        
            
        
    }//GEN-LAST:event_jTextFPagoKeyTyped

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getClickCount() == 2) {
             int rowIndex = this.jTable1.getSelectedRow();
        if(rowIndex >=0 ){
            int id = Integer.parseInt(this.jTable1.getValueAt(rowIndex, 0).toString());
            int cantidad = Integer.parseInt(this.jTable1.getValueAt(rowIndex, 6).toString());
            double descuento = monedaTransform.transfrormMoneda(this.jTable1.getValueAt(rowIndex, 7).toString());
            double valor = monedaTransform.transfrormMoneda(this.jTable1.getValueAt(rowIndex, 8).toString());
            setProductoVenta(id, cantidad, descuento, valor);
            this.listRegistroVendidos.remove(rowIndex);
            updateTable();
            
        }else{
            JOptionPane.showMessageDialog(null, "No ha selecionado ningun usuario para modificar", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
            
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        this.jTextFCodigo.setText("");
        this.jTextFCantidad.setText("");
        this.jTextFDescuento.setText("");
        this.jTextFDescripcion.setText("");
        this.jTextFValor.setText("");
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        this.jTextFCodigo.setText("");
        this.jTextFCantidad.setText("");
        this.jTextFDescuento.setText("");
        this.jTextFDescripcion.setText("");
        this.jTextFValor.setText("");
        this.jLTotal.setText("$");
        this.jLabel16.setText("$");
        this.jTextFPago.setText("");
        this.listRegistroVendidos.clear();
        updateTable();
    }//GEN-LAST:event_jLabel17MouseClicked
    public void setProductoVenta(int id){
        InventarioController inventarioController = new InventarioController();
        this.inventario = inventarioController.getProductoById(id);
        jTextFCodigo.setText(inventario.getCodigo().getCodigo());
        jTextFDescripcion.setText(inventario.getCodigo().getDescripcion());
        jTextFValor.setText(monedaTransform.formatMoneda(inventario.getValorVenta()));
    }
     public void setProductoVenta(int id, int cantidad, double descuento, double valor){
        InventarioController inventarioController = new InventarioController();
        this.inventario = null;
        this.inventario = inventarioController.getProductoById(id);
        jTextFCodigo.setText(inventario.getCodigo().getCodigo());
        jTextFDescripcion.setText(inventario.getCodigo().getDescripcion());
        jTextFValor.setText(monedaTransform.formatMoneda(valor));
        jTextFDescuento.setText(monedaTransform.formatMoneda(descuento));
        jTextFCantidad.setText(String.valueOf(cantidad));
    }
    
    private void updateTable(){
        DefaultTableModel model = (DefaultTableModel) this.jTable1.getModel();
        model.setNumRows(0);
        int item = 0;
        for(RegistroVendido registroVendido : this.listRegistroVendidos){
            item += 1;
            Object[] rowData = {
            registroVendido.getId(),
            item,
            registroVendido.getCodigo(),
            registroVendido.getDescripcion(),
            registroVendido.getTalla(),
            registroVendido.getColor(),
            registroVendido.getCantidad(),
            monedaTransform.formatMoneda(registroVendido.getDescuento()),
            monedaTransform.formatMoneda(registroVendido.getValorVenta())
            };
      model.addRow(rowData);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLRol;
    private javax.swing.JLabel jLTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioCredito;
    private javax.swing.JRadioButton jRadioSeparar;
    private javax.swing.JRadioButton jRadioVenta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFCantidad;
    private javax.swing.JTextField jTextFCodigo;
    private javax.swing.JTextField jTextFDescripcion;
    private javax.swing.JTextField jTextFDescuento;
    private javax.swing.JTextField jTextFPago;
    private javax.swing.JTextField jTextFValor;
    // End of variables declaration//GEN-END:variables
}
